version: '3.8'

services:
  inventory-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: inventory-service
    ports:
      - "8082:8082"
    environment:
      # Server Configuration
      INVENTORY_SERVER_HOST: "0.0.0.0"
      INVENTORY_SERVER_PORT: "8082"
      
      # Database Configuration (connect to external database)
      DB_HOST: "host.docker.internal"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres123"
      DB_NAME: "icecream_store"
      DB_SSLMODE: "disable"
      
      # Logging Configuration
      LOG_LEVEL: "info"
    
    # Health check
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8082/api/v1/inventory/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    # Restart policy
    restart: unless-stopped
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    
    # Networks
    networks:
      - inventory-network

networks:
  inventory-network:
    driver: bridge 