services:
  ui-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: icecream_ui
    restart: unless-stopped
    environment:
      # Gateway service URL (Docker internal network)
      GATEWAY_SERVICE_URL: ${GATEWAY_SERVICE_URL:-http://icecream_gateway:8082}
      
      # Environment
      NODE_ENV: ${NODE_ENV:-production}
      
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "http://127.0.0.1:3000/", "-O", "/dev/null"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - docker_icecream_network

networks:
  docker_icecream_network:
    external: true 