services:
  auth-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: icecream_auth
    restart: unless-stopped
    environment:
      # Server Configuration
      AUTH_SERVER_HOST: 0.0.0.0
      AUTH_SERVER_PORT: 8081
      
      # JWT Configuration
      JWT_SECRET: ${JWT_SECRET:-icecream-super-secret-jwt-key-change-in-production-2024}
      JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME:-10m}
      JWT_REFRESH_THRESHOLD: ${JWT_REFRESH_THRESHOLD:-2m}
      
      # Database Configuration (connect to existing data-service database)
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres123
      DB_NAME: icecream_store
      DB_SSLMODE: disable
      
      # Security Configuration
      BCRYPT_COST: ${BCRYPT_COST:-12}
      MAX_LOGIN_ATTEMPTS: ${MAX_LOGIN_ATTEMPTS:-5}
      LOGIN_COOLDOWN_TIME: ${LOGIN_COOLDOWN_TIME:-15m}
      
      # Logging Configuration
      LOG_LEVEL: ${LOG_LEVEL:-info}
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/api/v1/auth/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - docker_icecream_network

networks:
  docker_icecream_network:
    external: true 